// The app's 48 icons (docs/design/icons.json → icons-data.js, generated by scripts/site/data.mjs) as SVG markup.
//
//   icon('sound')                                   → '<svg …>' 24 px, stroke 1.75, currentColor, aria-hidden
//   icon('check', { size: 20, stroke: 2, label: 'Landed', class: 'x' })
//   el.innerHTML = icon('arrow-right');
//
// 24 grid, round caps and joins, no fills; dots are zero-length segments that render as round caps.
// Never below 16 px. No padlock exists in the set — locked is a dashed ghost, never a lock.

import ICONS from './icons-data.js';

export const iconNames = Object.keys(ICONS);

const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]);

/**
 * SVG markup for icon `name`. Options: size (px, default 24), stroke (default 1.75; 2 is allowed on coloured
 * fills), label (adds role="img" + aria-label; otherwise aria-hidden), class (extra class names).
 * Unknown names throw, so a typo shows up at once.
 */
export function icon(name, { size = 24, stroke = 1.75, label, class: cls } = {}) {
  const paths = ICONS[name];
  if (!paths) throw new Error(`icon: no "${name}" in the set (${iconNames.length} icons)`);
  const a11y = label ? `role="img" aria-label="${esc(label)}"` : 'aria-hidden="true" focusable="false"';
  return (
    `<svg class="icon${cls ? ` ${esc(cls)}` : ''}" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" ` +
    `stroke="currentColor" stroke-width="${stroke}" stroke-linecap="round" stroke-linejoin="round" ${a11y}>` +
    paths.map((d) => `<path d="${d}"/>`).join('') +
    `</svg>`
  );
}

/** Replaces every `<i data-icon="name" data-size="20">` inside `root` with its SVG (for static markup in partials). */
export function hydrateIcons(root = document) {
  for (const el of root.querySelectorAll('[data-icon]')) {
    const name = el.getAttribute('data-icon');
    if (!ICONS[name]) continue;
    const size = Number(el.getAttribute('data-size')) || 24;
    const stroke = Number(el.getAttribute('data-stroke')) || 1.75;
    el.outerHTML = icon(name, { size, stroke, label: el.getAttribute('aria-label') || undefined, class: el.className || undefined });
  }
}

export { ICONS };
